name: zip_comic_viewer
description: ZIP/CBZ 압축파일 이미지 뷰어

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 파일 선택
  file_picker: ^8.0.3
  
  # ZIP 압축 해제
  archive: ^3.4.10
  
  # 이미지 핀치줌
  photo_view: ^0.15.0
  
  # 로컬 데이터 저장 (북마크/마지막 페이지)
  shared_preferences: ^2.2.3
  
  # 파일 경로
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
